# docker-compose.yml
version: "3.8"

services:
  # Контейнер основной базы данных
  postgres:
    image: postgres:${POSTGRES_VERSION}
    container_name: schedule-postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  # Контейнер Redis DB для сохранения пользовательских сессий
  redis_sessions:
    image: redis:${REDIS_VERSION}
    container_name: schedule-redis-sessions
    restart: always
    # Заставляем redis использовать наш conf файл, а не стандартный
    command: ["redis-server", "/usr/local/etc/redis/redis.conf", "--requirepass", "${REDIS_PASSWORD}"]
    ports:
      # В проде, когда api будет работать внутри докера, нужно будет убрать порты
      - "127.0.0.1:${REDIS_SESSIONS_PORT}:6379"
    volumes:
      - ./redis/redis_sessions/redis.conf:/usr/local/etc/redis/redis.conf:ro
      - postgres_redis_sessions:/data
    
volumes:
  postgres_data:
  postgres_redis_sessions:
