"""create all main tables

Revision ID: 624fcbd053fb
Revises: a149868f4c6d
Create Date: 2026-07-19 01:49:55.281764

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '624fcbd053fb'
down_revision: str | Sequence[str] | None = 'a149868f4c6d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buildings',
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('number')
    )
    op.create_table('class_session_types',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('payment_forms',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('is_state_funded', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('specialties',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('teachers_categories',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('cabinets',
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('building_number', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['building_number'], ['buildings.number'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plans',
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('specialty_code', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['specialty_code'], ['specialties.code'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teachers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('surname', sa.String(length=100), nullable=False),
    sa.Column('lastname', sa.String(length=100), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('teacher_category', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['teacher_category'], ['teachers_categories.name'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chapter_in_plan',
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('groups',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('year_admission', sa.Integer(), nullable=False),
    sa.Column('count_students', sa.Integer(), nullable=False),
    sa.Column('group_advisor_id', sa.Integer(), nullable=True),
    sa.Column('specialty_code', sa.String(length=20), nullable=False),
    sa.Column('payment_form', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['group_advisor_id'], ['teachers.id'], onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['payment_form'], ['payment_forms.name'], onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['specialty_code'], ['specialties.code'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('semesters',
    sa.Column('semester_number', sa.Integer(), nullable=False),
    sa.Column('weeks', sa.Numeric(), nullable=False),
    sa.Column('practice_weeks', sa.Numeric(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cycle_in_chapter',
    sa.Column('contains_modules', sa.Boolean(), nullable=False),
    sa.Column('chapter_in_plan_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['chapter_in_plan_id'], ['chapter_in_plan.id'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subjects',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('alias', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('self_study_hours', sa.Integer(), nullable=False),
    sa.Column('lectures_hours', sa.Integer(), nullable=False),
    sa.Column('laboratory_hours', sa.Integer(), nullable=False),
    sa.Column('practical_hours', sa.Integer(), nullable=False),
    sa.Column('course_project_hours', sa.Integer(), nullable=False),
    sa.Column('consultation_hours', sa.Integer(), nullable=False),
    sa.Column('intermediate_assessment_hours', sa.Integer(), nullable=False),
    sa.Column('semester_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['semester_id'], ['semesters.id'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('certifications',
    sa.Column('subject_id', sa.BigInteger(), nullable=False),
    sa.Column('credit', sa.Boolean(), nullable=False),
    sa.Column('differentiated_credit', sa.Boolean(), nullable=False),
    sa.Column('course_project', sa.Boolean(), nullable=False),
    sa.Column('course_work', sa.Boolean(), nullable=False),
    sa.Column('control_work', sa.Boolean(), nullable=False),
    sa.Column('other_form', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('subject_id')
    )
    op.create_table('module_in_cycle',
    sa.Column('cycle_in_chapter_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['cycle_in_chapter_id'], ['cycle_in_chapter.id'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('streams',
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('group_id', sa.String(length=50), nullable=False),
    sa.Column('subject_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.name'], onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('number', 'group_id', 'subject_id')
    )
    op.create_table('teacher_assignments',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.BigInteger(), nullable=False),
    sa.Column('group_name', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['group_name'], ['groups.name'], onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('class_sessions',
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('teacher_assignment_id', sa.BigInteger(), nullable=False),
    sa.Column('cabinet_id', sa.Integer(), nullable=False),
    sa.Column('class_session_type', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['cabinet_id'], ['cabinets.id'], onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['class_session_type'], ['class_session_types.name'], onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_assignment_id'], ['teacher_assignments.id'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('refresh_tokens')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refresh_tokens',
    sa.Column('user_uuid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('token_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('expire_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('revoked', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('uuid', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_uuid'], ['users.uuid'], name=op.f('refresh_tokens_user_uuid_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid', name=op.f('refresh_tokens_pkey'))
    )
    op.drop_table('class_sessions')
    op.drop_table('teacher_assignments')
    op.drop_table('streams')
    op.drop_table('module_in_cycle')
    op.drop_table('certifications')
    op.drop_table('subjects')
    op.drop_table('cycle_in_chapter')
    op.drop_table('semesters')
    op.drop_table('groups')
    op.drop_table('chapter_in_plan')
    op.drop_table('teachers')
    op.drop_table('plans')
    op.drop_table('cabinets')
    op.drop_table('teachers_categories')
    op.drop_table('specialties')
    op.drop_table('payment_forms')
    op.drop_table('class_session_types')
    op.drop_table('buildings')
    # ### end Alembic commands ###
