"""fix class_session_type model, add bool field is_stream

Revision ID: 56abab7301d7
Revises: 624fcbd053fb
Create Date: 2026-08-06 21:47:23.333227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56abab7301d7'
down_revision: Union[str, Sequence[str], None] = '624fcbd053fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('class_session_types', sa.Column('is_stream', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('class_session_types', 'is_stream')
    # ### end Alembic commands ###
